sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: YAdncjKv8Ml+BhfdSYMNgqzhl4pcSDoCtNKKTjV02Wtv66igOKfaAMrbaUXbsMDCXRxArua7asewSfODhBOb3g7Iy9E6dLR1tY8FZ1ApPIkv1SnoGgTLMu/0J9dApVRCz8wQyEvlsu1K7c+szh0Nt96xJwtY8lF6L9QAAWla0L2HDhsXvy5ULFzS7Hz8zJa+TKp/9N2BSPijjRu4VgqVVxHtR1vrGsf5iSAuXQcYPDv6Vdpbs1eu5uUcrv0e2LPNZTJ2R8OY+crpfk5n+11UYp3ybr14y49B8unFU8p0NlquWfyDU/RnsQZXrW86x2BGq3QLsrPGfsp6uvdz6PUDeSKDWDkzu8aFXj0KVan4ZqxpSwoT5kPcIlaUGP22Gbh53vfI/egY2nmuWQ3jO2j3K9lzR/YYBjSx00PQRj6xUpsA4xoSoTA1vcQBertMYGi8nQMzMTmTqKGdoBfS6szQiQ1H22Am7wjwT00wfo33PIK454st1DR1OJuAvmQD1+FgSSgXcIFCzDLPo0DnCHZdugI4yUeLfOclqeOweK4IsWNS7r070AbmnAOuBLXI2+/cUmoePOj1UyRuoZe5KMLbk11ahGM9s4AR3v7Eufr6EXw0DbGsztkABHCv+toXEb2Af5+ic7tnl2pJ5NdwU3zvpDYLUapr9zC6bjYuC/lzvcU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Orange-Fairy-Book_3027
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy